project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "A Geospatial Analysis of EV Charging Station Distribution for Sustainable Urban Mobility in South Korea"
  author:
    - Jun Won Park (jp4474)
    - Sun Young Park (sp0525)
  repo-url: https://github.com/jp4474/EVChargingStations
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: lux
    code-fold: true


